### PR TITLE
Enabled Nav Mesh and implemented of_navmesh_spawns

### PR DESCRIPTION
**Pull request by Msalinas2877**
Selects random spawns using the navigation mesh, only for dm

### CODE REVIEW

**Comment by Nopey** [comment]
This can spawn players inside walls.
I've added a check for IsFlat, to stop players from spawning on stairs, and am about to check the players bounding box as well.

**Comment by Nopey** [comment]
PR https://github.com/Msalinas2877/Open-Fortress-Source/pull/1 opened to your branch, contains anti-stair and wall checks.
If this feature is desired, it should probably figure out what direction to face the player as well. (raycast in 8 or so directions and put the player's back to the shortest ray?)
From what I'm reading on the discords, this isn't likely to be merged.
Can you think of a compelling use-case for this feature?

**Comment by Nopey** [comment]
Also, I'm not convinced my fix will prevent the player from spawning inside a clip brush.

**Comment by Msalinas2877** [comment]
Nav areas should not exist inside clip brushes

**Comment by Nbc66** [comment]
Allso did you ackunt for nav mesehs being generated in the 3d skybox?

**Comment by Msalinas2877** [comment]
@Nbc66 In that case they should be removed manually, theres no reason for them to exist there

**Comment by Nbc66** [comment]
@msalinas2887 you should make it so no one can spawn behinde the playerclip of the spawn area or at least check if there is a spawn entitybin that area and make them spwan only in that area

**Comment by Nopey** [comment]
Okay, after some testing, no clip brush issues were discovered.
I'm gonna add code to face the player away from walls

**Comment by Nopey** [comment]
a spawnroom check is unnecessary IMO, because this cvar is only for deathmatch

**Pull request merged**
